spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_t?characterEncoding=UTF8&useSSL=false&serverTimeZone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8888
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_
  mapper-locations: classpath*:com.xixiy.blog/mapper/*.xml
